[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configuración de redirección después del envío del formulario
[[redirects]]
  from = "/pqrs/gracias"
  to = "/pqrs/success.html"
  status = 200

# Redirección para el envío exitoso de formularios Netlify
[[redirects]]
  from = "/thanks.html"
  to = "/pqrs/success.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de seguridad general
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://www.google.com https://translate.google.com https://www.gstatic.com https://translate.googleapis.com https://translate-pa.googleapis.com;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://www.gstatic.com;
      img-src 'self' data: https:;
      font-src 'self' https: data: https://fonts.gstatic.com;
      connect-src 'self' https://api.netlify.com https://translate.googleapis.com https://translate.google.com https://translate-pa.googleapis.com;
      form-action 'self' https://api.netlify.com;
      frame-src 'self' https://www.google.com https://translate.google.com https://translate-pa.googleapis.com https://www.youtube.com https://www.youtube-nocookie.com;
    """

# Configuración específica para el formulario PQRS
[[headers]]
  for = "/pqrs*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://www.google.com https://translate.google.com https://www.gstatic.com https://translate.googleapis.com;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://www.gstatic.com;
      img-src 'self' data: https:;
      font-src 'self' https: data:;
      connect-src 'self' https://api.netlify.com;
      form-action 'self' https://api.netlify.com;
      frame-src 'self' https://www.google.com https://translate.google.com;
    """
